image:
- Visual Studio 2019
- Ubuntu

init:
  - git config --global core.autocrlf input

services: 
- docker 

install:
- cmd: >-
    cd tests\RedisConfigs\3.0.503

    redis-server.exe --service-install --service-name "redis-6479" "..\Basic\master-6479.conf"

    redis-server.exe --service-install --service-name "redis-6480" "..\Basic\replica-6480.conf"

    redis-server.exe --service-install --service-name "redis-6481" "..\Basic\secure-6481.conf"

    redis-server.exe --service-install --service-name "redis-6482" "..\Failover\master-6482.conf"

    redis-server.exe --service-install --service-name "redis-6483" "..\Failover\replica-6483.conf"

    redis-server.exe --service-install --service-name "redis-7000" "..\Cluster\cluster-7000.conf" --dir "..\Cluster"

    redis-server.exe --service-install --service-name "redis-7001" "..\Cluster\cluster-7001.conf" --dir "..\Cluster"

    redis-server.exe --service-install --service-name "redis-7002" "..\Cluster\cluster-7002.conf" --dir "..\Cluster"

    redis-server.exe --service-install --service-name "redis-7003" "..\Cluster\cluster-7003.conf" --dir "..\Cluster"

    redis-server.exe --service-install --service-name "redis-7004" "..\Cluster\cluster-7004.conf" --dir "..\Cluster"

    redis-server.exe --service-install --service-name "redis-7005" "..\Cluster\cluster-7005.conf" --dir "..\Cluster"

    redis-server.exe --service-install --service-name "redis-7010" "..\Sentinel\redis-7010.conf"

    redis-server.exe --service-install --service-name "redis-7011" "..\Sentinel\redis-7011.conf"

    redis-server.exe --service-install --service-name "redis-26479" "..\Sentinel\sentinel-26479.conf" --sentinel

    redis-server.exe --service-install --service-name "redis-26480" "..\Sentinel\sentinel-26480.conf" --sentinel
    
    redis-server.exe --service-install --service-name "redis-26481" "..\Sentinel\sentinel-26481.conf" --sentinel

    cd ..\..\..
- sh: >-
    sudo curl -L https://github.com/docker/compose/releases/download/1.26.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

    sudo chmod +x /usr/local/bin/docker-compose

    sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

    cd tests/RedisConfigs

    docker-compose up -d

    cd ../..
- ps: >-
    if (Get-Command "Start-Service" -errorAction SilentlyContinue) {
      Start-Service redis-*
    }

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - docs/*

environment:
  Appveyor: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

nuget:
  disable_publish_on_pr: true

build_script:
- ps: .\build.ps1 -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -CreatePackages ($env:OS -eq "Windows_NT")

test: off
artifacts:
- path: .\.nupkgs\*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/stackoverflow/api/v2
  on:
    branch: main
  api_key:
    secure: P/UHxq2DEs0GI1SoDXDesHjRVsSVgdywz5vmsnhFQQY5aJgO3kP+QfhwfhXz19Rw
  symbol_server: https://www.myget.org/F/stackoverflow/symbols/api/v2/package